apiVersion: v2
name: forensics-challenge
description: A Helm chart for deploying forensics security challenges
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - security
  - ctf
  - forensics
  - challenge
maintainers:
  - name: Gabriel Mocanu
